user:
  #username 学号或者工号
  username: '2002020204052'
  #tellphone 电话号码
  tellphone: '19837836685'
  #address 地址，定位信息
  address: 河南省开封市尉氏县铁路北街77号
  #email 接受通知消息的邮箱
  email: 3404210434@qq.com
  #school 学校全称
  school: 河南牧业经济学院
  #lon 当前位置经度
  lon: '114.209380'
  #lat 当前位置纬度
  lat: '34.403064'
  #abnormalReason 反馈信息，不需要可不填
  abnormalReason: 在家
  #photo 签到照片，不需要可不填
  photo:
#今日校园相关配置
cpdaily:
  #附加信息组默认选项配置，没有可留空
  defaults:
    #附加信息组默认选项配置，按顺序，可留空
    - default:
        title: 晚检体温(必填)
        value: 小于37.3度
    - default:
        title: 是否有发热、咳嗽、乏力、呼吸困难等疑似症状(必填)
        value: 否
